import Head from 'next/head'
import Footer from '../components/layout/Footer'
import NavigationBar from '../components/layout/NavigationBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="wrapper dark">
      <Head>
        <title>Damilola Oluwafemi | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>hello</main>
    </div>
  )
}
